apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: retrieval-svc
  title: Retrieval service template (Jenkins)
  description: Provisions a minimalistic retrieval svc
spec:
  owner: development
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - environment
      properties:
        component_id:
          title: Component name
          type: string
          description: Provide a component (microservice) name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        environment:
          title: Environment
          type: string
          description: The environment where this component will be deployed
          enum:
            - dev
            - prod
        topK:
          title: Top k to retrieve
          type: number
          description: Top number of similar chunks to retreive (typically 3, odd number)
        metric:
          title: Metric
          type: enum
          description: Similarity metric to use
          enum:
            - dot
            - euclidean
            - cosine

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{parameters.component_id}}
          app_env: ${{parameters.environment}}
          model_provider: ${{parameters.model_provider}}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.component_id }}
        repoUrl: github.com?owner=arjun-mindsprint-udemy&repo=${{parameters.component_id}}
        protectDefaultBranch: false
        repoVisibility: public

    - id: register-component
      name: Register Component in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: register-api
      name: Register API in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/openapi.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
