apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Node app named ${{values.app_name}}
  annotations:
    github.com/project-slug: arjun-mindsprint-udemy/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
    jenkins.io/job-full-name: node-app-test-folder/${{values.app_name}}
spec:
  type: service
  owner: development
  lifecycle: experimental
  providesApis:
    - ${{values.app_name}}-api