apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: embedding-svc
  title: Vector DB service template (Jenkins)
  description: Provisions a minimalistic vectordb svc
spec:
  owner: development
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - environment
      properties:
        component_id:
          title: Component name
          type: string
          description: Provide a component (microservice) name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        environment:
          title: Environment
          type: string
          description: The environment where this component will be deployed
          enum:
            - dev
            - prod
        pgvector_url:
          title: Your Postgres URL
          type: string
          description: Follows this format- 'postgresql://{your_username}:{your_password}@localhost:5432/{your_db}'
        redis_url:
          title: Your Redis URL
          type: string
          description: Follows this format- 'redis://localhost:6379'
        db_type:
          title: Preferred Vector DB
          type: string
          description: Preferred Vector DB
          enum:
            - pgvector
            - redis
            - array

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{parameters.component_id}}
          app_env: ${{parameters.environment}}
          model_provider: ${{parameters.model_provider}}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.component_id }}
        repoUrl: github.com?owner=arjun-mindsprint-udemy&repo=${{parameters.component_id}}
        protectDefaultBranch: false
        repoVisibility: public

    - id: register-component
      name: Register Component in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: register-api
      name: Register API in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/openapi.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
